name: kerberosio # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '3.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A stand-alone open source video surveillance system # 79 char long summary
description: |
   Kerberos Agent is an isolated and scalable video (surveillance) management
   agent made available as Open Source under the MIT License. This means that
   all the source code is available for you or your company, and you can use,
   transform and distribute the source code; as long you keep a reference of
   the original license. Kerberos Agent can be used for commercial usage.

grade: stable # stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
environment:
  GIN_MODE: release
apps:
  agent:
    command: main -config /var/snap/kerberosio/common
    plugs: [ network, network-bind ]
parts:
  agent:
    source: . #https://github.com/kerberos-io/agent/releases/download/21c0e01/agent-amd64.tar
    plugin: dump